fix #1520: adding a new item that results in displaying 3 items in the UI.
sneat-co/sneat-apps pull request #1524
Opened 2023-11-13 20:03 UTC by CodeNinja-Pro

This pull request addresses this issue #1520

2023-11-14 08:45 UTC, trakhimenok requested changes

2023-11-14 08:45 UTC, trakhimenok commented on libs/extensions/listus/src/lib/pages/list/list-page.component.ts
> +			this.listItems = [...this.addingItems];
This looks wrong. If we had [item1, item2] and adding [item3] it will result in first 2 items disappear from the list?

2023-11-14 09:14 UTC, CodeNinja-Pro commented on libs/extensions/listus/src/lib/pages/list/list-page.component.ts
> +			this.listItems = [...this.addingItems];
Have you checked it in the browser?
If there are already items present, when I add a new item, it will be appended to the existing list of items.

2023-11-14 09:29 UTC, trakhimenok commented on libs/extensions/listus/src/lib/pages/list/list-page.component.ts
> +			this.listItems = [...this.addingItems];
No, I did not had a chance but I guess in browser it can be unnoticable when running locally as once we get update from new record from Firestore it will be overridden and you would not have time to notice.

Though it might flicker in real life on slow connection

I'm pretty sure if you disable update after submitting new item you'll see the issue. Or you can add a delay in pipeline of subscribing to the List record

Ideally uni test should verify for N=[0, 2]:

N items before submit
N+1 items after submit but before we got record refresh
N+1 items after record refhresh

2023-11-18 10:50 UTC, trakhimenok commented
@CodeNinja-Pro please rebase you branch on top of latest main

2023-11-19 08:03 UTC, trakhimenok commented
Superseded by https://github.com/sneat-co/sneat-apps/pull/1541

2023-11-19 08:03 UTC, closed without merging