e2e #1521: added Cypress tests to project and CI build
sneat-co/sneat-apps pull request #1529
Opened 2023-11-15 07:27 UTC by AlmaniaM

This pull request addresses the ci(e2e) requirements of this issue #1521

What I added:
- Cypress tests in sneat-apps.
- Cypress test run in the CI build.
- Five different e2e tests to get thigs started.
- Custom commands for initializing firebase, delete user data, login, logout, etc...
- A few different commands to run tests headless as well as UI mode.

2023-11-15 09:48 UTC, trakhimenok requested changes

2023-11-15 09:48 UTC, trakhimenok commented on .github/workflows/ci.yml
> +      - run: pnpm install -g firebase-tools
Seeing in console:

`It appears you are running in a CI environment. You can avoid downloading the Emulator UI repeatedly by caching the /home/runner/.cache/firebase/emulators directory.`

Can you add the path to the cash step just above? Maybe the cache step name also need to be changed to reflect it takes care of more than just PNPM store dir.

2023-11-15 09:48 UTC, trakhimenok commented on .github/workflows/ci.yml
> +        run: git clone https://github.com/sneat-co/sneat-go-backend.git
Probably out of scope for the current task but it would be cool if we can download only content of latest tag like https://stackoverflow.com/a/73853582/1975086 - probably would require a step to retrieve latest tag like https://github.com/marketplace/actions/get-latest-tag. Maybe there is a ready action for this.

2023-11-15 09:48 UTC, trakhimenok commented on apps/sneat-app/cypress/e2e/commune/commune-setup.e2e.spec.ts
> +describe('Commune Setup', () => {
Isn't it a duplicate of create_team in team-setup.e2e.spec.ts?

The `commune` folder is outdated legacy and should not be used if possible. It would be good if we can move tests  to team(s) or some other places.

2023-11-15 09:48 UTC, trakhimenok commented on apps/sneat-app/cypress/fixtures/example.json
> +	"email": "hello@cypress.io",
I'd suggest to use cypress@example.com to make sure we accidentally do not spam to `hello@cypress.io`

2023-11-15 09:52 UTC, trakhimenok commented on .github/workflows/ci.yml
> +      - name: Run Cypress tests
Can we add a build step before running tests to exclude build time from tests times? I'd like to see timing as close to time spent on actual testing as possible.

2023-11-15 09:53 UTC, trakhimenok commented on .github/workflows/ci.yml
> +          pnpm install --force
What does `--force` mean and do we really need it?

2023-11-15 14:22 UTC, AlmaniaM commented on .github/workflows/ci.yml
> +        run: git clone https://github.com/sneat-co/sneat-go-backend.git
I think we can just do `git clone https://github.com/sneat-co/sneat-go-backend.git -b main --single-branch --depth 1`. This should only clone main with a single commit (latest).

2023-11-15 14:25 UTC, AlmaniaM commented on .github/workflows/ci.yml
> +          pnpm install --force
This will force `pnpm` to ignore any outdated dependencies. Currently, `@angular/fire` hasn't been updated to Angular 17 so without it the `install` fails. It can be removed once `@angular/fire` is updated.

2023-11-15 14:31 UTC, AlmaniaM commented on apps/sneat-app/cypress/e2e/commune/commune-setup.e2e.spec.ts
> +describe('Commune Setup', () => {
What are you referring to, the test itself or the concept of team vs commune? The tests do two different things. The new_team test is a simple test that makes sure a new team is quickly created by clicking the new team button. The commune test goes through the "Create a family" process.

2023-11-15 14:32 UTC, AlmaniaM commented on .github/workflows/ci.yml
> +      - name: Run Cypress tests
Are you saying to add a build step the launches the Firebase emulators and sneat-go-backend in a separate build before the `cypress-e2e`?

2023-11-15 15:59 UTC, trakhimenok commented on .github/workflows/ci.yml
> +          pnpm install --force
It's fine, thanks. I'd appreciate if you can add this explantion as a comment to the ci.yml

2023-11-15 16:36 UTC, trakhimenok commented on .github/workflows/ci.yml
> +        run: git clone https://github.com/sneat-co/sneat-go-backend.git
Alex, can you please do that, and once all other comments addressed to let me know?

I might not be able to review today as I going to go sleep earlier today but I'll try to do 1st thing in my morning.

2023-11-15 16:37 UTC, trakhimenok commented on apps/sneat-app/cypress/e2e/commune/commune-setup.e2e.spec.ts
> +describe('Commune Setup', () => {
Not sure I folllow but anyway it's not a deal-breaker and I'm OK to accept as is for now.

2023-11-16 07:55 UTC, trakhimenok submitted a review, later dismissed

2023-11-16 07:58 UTC, trakhimenok commented
@AlmaniaM can you please rebase your branch & resolve conflicts in package.json & pnpm-lock?

After that I'm good go merge.

2023-11-16 16:22 UTC, trakhimenok submitted a review, later dismissed

2023-11-16 16:27 UTC, trakhimenok commented
@AlmaniaM still failing :(

2023-11-16 16:29 UTC, AlmaniaM commented
Yeah I didn't mean to push that one up. Still working on it.

2023-11-16 18:53 UTC, AlmaniaM commented
@trakhimenok Okay, this was passing a couple times for me. Let's see how it goes here. Cypress keeps having a hard time recognizing a served application but should be good now.

2023-11-16 20:54 UTC, trakhimenok approved these changes

2023-11-16 20:54 UTC, merged

2023-11-16 20:56 UTC, trakhimenok commented
@AlmaniaM merged. I’ll close the job tomorrow as now have no access from phone.

thanks a lot!

2023-11-16 20:58 UTC, AlmaniaM commented
Sounds good, no worries!