feat: add components to add dwelling
sneat-co/sneat-apps pull request #1975
Opened 2024-05-29 08:54 UTC by xspace-solution

2024-05-29 09:27 UTC, trakhimenok requested changes

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/add-dwelling-card/add-dwelling-card.component.ts
> +			this.dwellingAsset?.dto?.extra &&
First 2 checks are redundant as the 3d uses '?.' notation.

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/add-dwelling-card/add-dwelling-card.component.ts
> +	countryChanged(value: string): void {
Naming convention on this project to name event handlers with on prefix, like onCoubtryChanged

Also can be protected?

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/asset-add/asset-add-dwelling/asset-add-dwelling.component.ts
> +	submitDwellingForm(): void {
Can be protected?

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/asset-add/asset-add-dwelling/asset-add-dwelling.component.ts
> +			throw 'no dwellingType';
Wrap with new Error() for consistency here and everywhere else

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/asset-add/asset-add-dwelling/asset-add-dwelling.component.ts
> +	protected readonly id = (_: number, o: { id: string }) => o.id;
Please remove this one and use latest @for Angular syntax for iterating in templates

2024-05-29 09:27 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/add-dwelling-card/add-dwelling-card.component.ts
> +	public area = '';
Should be number? Also rename to areaSqM so it's clear unit of measurement.

2024-05-30 07:34 UTC, trakhimenok requested changes

2024-05-30 07:34 UTC, trakhimenok commented on libs/extensions/assetus/components/src/lib/add-dwelling-card/add-dwelling-card.component.ts
> +		this.title = this.dwellingAsset?.dto?.title || '';
I think this was supposed to be an `EditDwellingCardComponent` and not the "Add" component? Otherwise assignments does not make sense (always empty on add).

Also if it's an edit component this assignments should be moved from `constructor` to `ngOnChange`

2024-05-30 08:56 UTC, xspace-solution commented on libs/extensions/assetus/components/src/lib/asset-add/asset-add-dwelling/asset-add-dwelling.component.ts
> +			throw 'no dwellingType';
Added new Error() object

2024-05-30 09:00 UTC, trakhimenok approved these changes

2024-05-30 09:09 UTC, merged